### ISSUE TITLE
Victron app crashes and no data

### ISSUE THREAD

**Issue by harmlutjeboer** [ricott/homey-com.victronenergy#6]
Hi, 

Yesterday I installed the victron app on my Homey, but it does not work the way I aspect it. It looks like there are 2 problems right now.

1: I can't see any data form my Cerbo GX device. Everything is at zero, so it seems there is no data comming back from the Cerbo to the homey. I can control the Cerbo from the Homey. I made a flow that switches one of te relays on the Cerbo and that seems to work just fine.
![data](https://user-images.githubusercontent.com/25951139/160587366-d8ab45b8-c57d-4cd8-9726-cb45c9159f22.JPG)

![WhatsApp Image 2022-03-29 at 12 11 05 PM](https://user-images.githubusercontent.com/25951139/160589058-ae3bc166-0326-4802-a29e-1b9237baa6b9.jpeg)

2. The app crashes when running for about 5 minutes. The cerbo is getting a red X in the device list. After restarting the app it works again. 

![WhatsApp Image 2022-03-29 at 12 11 05 PM(3)](https://user-images.githubusercontent.com/25951139/160589294-0a81d3e4-daf6-4a71-8cea-2b2484d3d72f.jpeg)
![WhatsApp Image 2022-03-29 at 12 11 05 PM(1)](https://user-images.githubusercontent.com/25951139/160589348-16d429b2-67b4-4d13-bfe0-b3858fa107ff.jpeg)
 

I hope you can help me out!

Greetings from the Netherlands.

Harm Lutjeboer

**Comment by ricott** [comment]
Hi there!

You could potentially be the one that shared a diagnostic report with me yesterday? I tried to reply to it but somehow the email was rejected from Athom. Anyhow, the below is what I wrote in the email

Hi!

I see lots of errors like the below in the attached logs. I think you need to verify your unit id values.
com.victronenergy.system should always be 100, this I set statically in the code - nothing you provide.
com.victronenergy.vebus could be 227 as you have tried with, but you need to verify with your GX device what is actually used.
com.victronenergy.battery you may have or not have, but I'm pretty sure it is not 100 at least that I see in the logs.

```
[err] 2022-03-28 20:53:12 [ManagerDrivers] [Driver:gx] [Device:0e408f02-e470-4447-a449-790b9814a9e8] Houston we have a problem Error: Failed to read '289' with unitId 'battery/227' for device type 'n/a'
    at modbusReading (/lib/victron.js:357:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

There is a short text here, https://community.homey.app/t/app-pro-victron-energy/46219#need-to-know-before-adding-a-gx-device-to-your-homey-4
On my device it looks like this

![image](https://user-images.githubusercontent.com/31240726/160594438-32899995-8f50-4aa6-bdad-816c2ff38b21.png)

![image](https://user-images.githubusercontent.com/31240726/160594471-7df8b740-41d6-46fe-8c91-041a4fe4864b.png)

**Comment by harmlutjeboer** [comment]
Sorry, forget to add the screenshots. Here they are...

[cid:b8cb9cd8-3d33-4f42-b573-24b96aaeef20][cid:af4261e6-3aa0-4a7c-8ab4-267edc2e7b6a][cid:beb8eb7b-f33d-4ed0-8fa3-438c336693fe]
________________________________
Van: Richard Barkestam ***@***.***>
Verzonden: dinsdag 29 maart 2022 12:44
Aan: ricott/homey-com.victronenergy ***@***.***>
CC: harmlutjeboer ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ricott/homey-com.victronenergy] Victron app crashes and no data (Issue #6)


Hi there!

You could potentially be the one that shared a diagnostic report with me yesterday? I tried to reply to it but somehow the email was rejected from Athom. Anyhow, the below is what I wrote in the email

Hi!

I see lots of errors like the below in the attached logs. I think you need to verify your unit id values.
com.victronenergy.system should always be 100, this I set statically in the code - nothing you provide.
com.victronenergy.vebus could be 227 as you have tried with, but you need to verify with your GX device what is actually used.
com.victronenergy.battery you may have or not have, but I'm pretty sure it is not 100 at least that I see in the logs.

[err] 2022-03-28 20:53:12 [ManagerDrivers] [Driver:gx] [Device:0e408f02-e470-4447-a449-790b9814a9e8] Houston we have a problem Error: Failed to read '289' with unitId 'battery/227' for device type 'n/a'
    at modbusReading (/lib/victron.js:357:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


There is a short text here, https://community.homey.app/t/app-pro-victron-energy/46219#need-to-know-before-adding-a-gx-device-to-your-homey-4
On my device it looks like this

[image]<https://user-images.githubusercontent.com/31240726/160594438-32899995-8f50-4aa6-bdad-816c2ff38b21.png>

[image]<https://user-images.githubusercontent.com/31240726/160594471-7df8b740-41d6-46fe-8c91-041a4fe4864b.png>

**Comment by KajLehtinen** [comment]
Same error for me, i'e app crashes frequently. With the last api error beeing the same 2901 and id 227. Have verified my IDs and they are right, worked fine with v1.03

**Comment by KajLehtinen** [comment]
Onething that i noticed is that when the error frequency went up i had rebooted my GX, and if I rebooted it a second time the errors seems to fade away, atleast its been stable for 12h+ now.

Perhaps a issue in 2.84 Venus OS that occurs at some reboots?

**Comment by ricott** [comment]
@harmlutjeboer Seems like images added to emails don't show up on GitHub.
@KajLehtinen I use v2.84 myself as well. Yesterday I noticed that the app had stopped working, for the first time in a very long time. I'm pretty dependent on the app myself since I use it to control the charge current.

Don't know if any of you are able to install the app via CLI, `homey app run` and see what the app writes when it stops. The diagnostic reports from Homey are in 99 of 100 cases worthless. They are either empty or contain some log outputs from when the app was started.

**Comment by KajLehtinen** [comment]
is a CLI install done through SSH or how do one attach to the device? Mine has been stable since I rebooted Cerbo GX. Will try to reboot the Cerbo once more later in the week to see if the error comes back every other reboot.

/Kaj

**Comment by ricott** [comment]
Have you had any success with the app?

**Comment by harmlutjeboer** [comment]
Hi Richard,

I was indeed the one that shared a diagnostic report to you.

I have found the text already and fill in the ID's. I've send you some screenshots from my GX device. As you can see, the battery ID is also 100, the same as the system ID. Is there a wat to change the ID manualy, so I can be shure they dont conflict with eachother?

Hope you can help me out.

Greetings

Harm Lutjeboer
________________________________
Van: Richard Barkestam ***@***.***>
Verzonden: dinsdag 29 maart 2022 12:44
Aan: ricott/homey-com.victronenergy ***@***.***>
CC: harmlutjeboer ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ricott/homey-com.victronenergy] Victron app crashes and no data (Issue #6)


Hi there!

You could potentially be the one that shared a diagnostic report with me yesterday? I tried to reply to it but somehow the email was rejected from Athom. Anyhow, the below is what I wrote in the email

Hi!

I see lots of errors like the below in the attached logs. I think you need to verify your unit id values.
com.victronenergy.system should always be 100, this I set statically in the code - nothing you provide.
com.victronenergy.vebus could be 227 as you have tried with, but you need to verify with your GX device what is actually used.
com.victronenergy.battery you may have or not have, but I'm pretty sure it is not 100 at least that I see in the logs.

[err] 2022-03-28 20:53:12 [ManagerDrivers] [Driver:gx] [Device:0e408f02-e470-4447-a449-790b9814a9e8] Houston we have a problem Error: Failed to read '289' with unitId 'battery/227' for device type 'n/a'
    at modbusReading (/lib/victron.js:357:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


There is a short text here, https://community.homey.app/t/app-pro-victron-energy/46219#need-to-know-before-adding-a-gx-device-to-your-homey-4
On my device it looks like this

[image]<https://user-images.githubusercontent.com/31240726/160594438-32899995-8f50-4aa6-bdad-816c2ff38b21.png>

[image]<https://user-images.githubusercontent.com/31240726/160594471-7df8b740-41d6-46fe-8c91-041a4fe4864b.png>

**Comment by ricott** [comment]
If you install the test version of the app and then set the battery id to `-1`, it should work fine. 
I have had other users test this with success. The only lost functionality is a condition to check `Time since last full charge (s)`.

Will see if I find a way to work around conflicting ID's

**Comment by ricott** [comment]
Should be resolved in the latest [test version](https://homey.app/a/com.victronenergy/test/).
